TID: [-1] [] [2021-05-23 00:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 00:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 00:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 00:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 01:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 01:13:33,139]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on retrieving metadata within a range from queue.  
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:810)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:200)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:13:33,141] ERROR {org.wso2.andes.kernel.MessageHandler} -  error occurred retrieving metadata list for slot : Slot{messageCount=0, startMessageId=86186237726294017, endMessageId=86186239062179840, storageQueueName='logqueue', isSlotActive=true, isAnOverlappingSlot=false, slotStates=[CREATED], destinationOfMessagesInSlot='logqueue', pendingMessageCount=0}, retry count = 1 
org.wso2.andes.kernel.AndesException: Error occurred while retrieving messages between msg id 86186237726294017 and 86186239062179840 from queue logqueue
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:811)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:200)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:297)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeQuery(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:789)
	... 13 more
TID: [-1] [] [2021-05-23 01:13:33,144]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on retrieving metadata within a range from queue.  
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:810)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:223)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:13:33,145] ERROR {org.wso2.andes.kernel.slot.DeliveryTaskExceptionHandler} -  Error occurred while processing task. Task id logqueue 
org.wso2.andes.kernel.AndesException: Error occurred while retrieving messages between msg id 86186237726294017 and 86186239062179840 from queue logqueue
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:811)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:223)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:297)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeQuery(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:789)
	... 13 more
TID: [-1] [] [2021-05-23 01:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 01:36:55,280]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Error occurred while inserting message list. Messages will be stored individually. 
java.sql.BatchUpdateException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1870)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeBatch(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.prepareToStoreMessages(RDBMSMessageStoreImpl.java:443)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:392)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,282]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding metadata. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:401)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,284]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding message. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:502)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,285]  WARN {org.wso2.andes.kernel.disruptor.inbound.MessageWriter} -  Unable to store messages, due to errors in message stores. operatation will be reattempted. messages count : 1 
TID: [-1] [] [2021-05-23 01:36:55,285] ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} -  [ Sequence: 4695684 ] Exception occurred while processing inbound events.Event type: MESSAGE_EVENT 
org.wso2.andes.kernel.AndesException: Error occurred while inserting message to queue 
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:497)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:367)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.execute(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:478)
	... 10 more
TID: [-1] [] [2021-05-23 01:36:55,286]  INFO {org.wso2.andes.kernel.disruptor.inbound.MessageWriter} -  Attempting to store previously failed list of messages of size: 1 
TID: [-1] [] [2021-05-23 01:36:55,286]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Error occurred while inserting message list. Messages will be stored individually. 
java.sql.BatchUpdateException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1870)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeBatch(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.prepareToStoreMessages(RDBMSMessageStoreImpl.java:443)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:392)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,287]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding metadata. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:401)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,302]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding message. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:502)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,303] ERROR {org.wso2.andes.kernel.disruptor.inbound.MessageWriter} -  errors encountered while persisting previously failed messages batch,  this incident will result messages being lost 
org.wso2.andes.kernel.AndesException: Error occurred while inserting message to queue 
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:497)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:367)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.execute(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:478)
	... 10 more
TID: [-1] [] [2021-05-23 01:36:55,383]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Error occurred while inserting message list. Messages will be stored individually. 
java.sql.BatchUpdateException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1870)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeBatch(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.prepareToStoreMessages(RDBMSMessageStoreImpl.java:443)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:392)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,385]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding metadata. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:401)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,387]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding message. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:502)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:55,387]  WARN {org.wso2.andes.kernel.disruptor.inbound.MessageWriter} -  Unable to store messages, due to errors in message stores. operatation will be reattempted. messages count : 1 
TID: [-1] [] [2021-05-23 01:36:55,387] ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} -  [ Sequence: 4695686 ] Exception occurred while processing inbound events.Event type: MESSAGE_EVENT 
org.wso2.andes.kernel.AndesException: Error occurred while inserting message to queue 
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:497)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:100)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:367)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.execute(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:478)
	... 10 more
TID: [-1] [] [2021-05-23 01:36:56,275]  INFO {org.wso2.andes.kernel.disruptor.inbound.MessageWriter} -  Attempting to store previously failed list of messages of size: 1 
TID: [-1] [] [2021-05-23 01:36:56,278]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Error occurred while inserting message list. Messages will be stored individually. 
java.sql.BatchUpdateException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1870)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeBatch(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.prepareToStoreMessages(RDBMSMessageStoreImpl.java:443)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:392)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:56,280]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding metadata. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:401)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:56,282]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on adding message. 
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:502)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:56,283] ERROR {org.wso2.andes.kernel.disruptor.inbound.MessageWriter} -  errors encountered while persisting previously failed messages batch,  this incident will result messages being lost 
org.wso2.andes.kernel.AndesException: Error occurred while inserting message to queue 
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:497)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessages(RDBMSMessageStoreImpl.java:404)
	at org.wso2.andes.store.FailureObservingMessageStore.storeMessages(FailureObservingMessageStore.java:123)
	at org.wso2.andes.kernel.MessagingEngine.messagesReceived(MessagingEngine.java:172)
	at org.wso2.andes.kernel.disruptor.inbound.MessageWriter.writeMessages(MessageWriter.java:87)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:137)
	at org.wso2.andes.kernel.disruptor.ConcurrentBatchEventHandler.onEvent(ConcurrentBatchEventHandler.java:40)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:367)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.execute(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.storeMessage(RDBMSMessageStoreImpl.java:478)
	... 10 more
TID: [-1] [] [2021-05-23 01:36:58,235]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on retrieving metadata within a range from queue.  
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:810)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:200)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:58,236] ERROR {org.wso2.andes.kernel.MessageHandler} -  error occurred retrieving metadata list for slot : Slot{messageCount=0, startMessageId=86186606068236289, endMessageId=86186607346974720, storageQueueName='logqueue', isSlotActive=true, isAnOverlappingSlot=false, slotStates=[CREATED], destinationOfMessagesInSlot='logqueue', pendingMessageCount=0}, retry count = 1 
org.wso2.andes.kernel.AndesException: Error occurred while retrieving messages between msg id 86186606068236289 and 86186607346974720 from queue logqueue
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:811)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:200)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:297)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeQuery(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:789)
	... 13 more
TID: [-1] [] [2021-05-23 01:36:58,238]  WARN {org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl} -  Rollback failed on retrieving metadata within a range from queue.  
com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:279)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:36)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:2495)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:2500)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:2703)
	at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:127)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:153)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:41)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:80)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80)
	at com.sun.proxy.$Proxy14.rollback(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.rollback(RDBMSMessageStoreImpl.java:1534)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:810)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:223)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2021-05-23 01:36:58,238] ERROR {org.wso2.andes.kernel.slot.DeliveryTaskExceptionHandler} -  Error occurred while processing task. Task id logqueue 
org.wso2.andes.kernel.AndesException: Error occurred while retrieving messages between msg id 86186606068236289 and 86186607346974720 from queue logqueue
	at org.wso2.andes.store.rdbms.RDBMSStoreUtils.convertSQLException(RDBMSStoreUtils.java:128)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:811)
	at org.wso2.andes.store.FailureObservingMessageStore.getMetadataList(FailureObservingMessageStore.java:206)
	at org.wso2.andes.kernel.MessageHandler.readMessagesFromMessageStore(MessageHandler.java:223)
	at org.wso2.andes.kernel.MessageHandler.bufferMessages(MessageHandler.java:156)
	at org.wso2.andes.kernel.subscription.StorageQueue.loadMessagesForDelivery(StorageQueue.java:369)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:97)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: SHUTDOWN is in progress.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:297)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy15.executeQuery(Unknown Source)
	at org.wso2.andes.store.rdbms.RDBMSMessageStoreImpl.getMetadataList(RDBMSMessageStoreImpl.java:789)
	... 13 more
TID: [-1] [] [2021-05-23 01:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 01:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 02:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 02:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 02:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 02:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 03:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 03:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 03:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 03:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 04:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 04:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 04:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 04:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 05:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 05:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 05:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 05:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 06:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 06:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 06:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 06:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 07:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 07:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 07:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 07:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 08:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 08:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 08:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 08:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 09:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 09:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 09:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 09:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 10:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 10:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 10:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 10:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 11:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 11:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 11:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 11:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 12:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 12:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 12:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 12:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 13:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 13:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 13:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 13:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 14:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 14:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 14:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 14:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 15:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 15:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 15:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 15:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 16:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 16:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 16:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 16:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 17:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 17:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 17:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 17:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 18:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 18:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 18:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 18:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 19:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 19:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 19:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 19:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 20:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 20:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 20:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 20:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 21:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 21:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 21:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 21:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 22:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 22:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 22:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 22:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 23:07:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 23:22:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 23:37:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
TID: [-1] [] [2021-05-23 23:52:47,259]  WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store. 
